### ISSUE TITLE
FrameProcessor works, but just generates random characters

### ISSUE THREAD

**Issue by mschmid** [gev2002/react-native-vision-camera-v3-text-recognition#1]
Hi, I managed to get this frameProcessor running without `react-native-reanimated`. I used 
```
    "react-native-vision-camera": "3.9.2",
    "react-native-vision-camera-v3-text-recognition": "1.0.4",
    "react-native-worklets-core": "0.4.0",
```

I tried with the following settings:
```
const device = useCameraDevice('back', { physicalDevices: ['ultra-wide-angle-camera', 'wide-angle-camera'] })
<Camera
    audio={false}
    callback={(data: object) => onTextRecognized(data)}
    device={device}
    fps={30}
    isActive={visible}
    options={{
      language: 'latin',
    }}
    pixelFormat='yuv'
    resizeMode='cover'
    style={{
      height: 400,
      alignItems: 'center',
      width: '90%',
    }}
>
```

However, I just get random output:

```
size: 14
blockFrameBottom: 1127
blockFrameLeft: 964
blockFrameRight: 971
blockFrameTop: 1120
blockText: V
elementFrameBottom: 1127
elementFrameLeft: 964
elementFrameRight: 971
elementFrameTop: 1120
elementText: V
lineFrameBottom: 1127
lineFrameLeft: 964
lineFrameRight: 971
lineFrameTop: 1120
lineText: V
resultText: V
size: 7
blockFrameBottom: 1136
blockFrameLeft: 1040
blockFrameRight: 1052
blockFrameTop: 1126
blockText: A
elementFrameBottom: 1136
elementFrameLeft: 1040
elementFrameRight: 1052
elementFrameTop: 1126
elementText: A
lineFrameBottom: 1136
lineFrameLeft: 1040
lineFrameRight: 1052
lineFrameTop: 1126
lineText: A
resultText: M
 ```
 
 I tried with all orientations.
 Can you give some advice on how to configure camera (e.g. resolution, aspect ratio, fps, pixel format) to get the best results?

**Comment by gev2002** [comment]
> Hi, I managed to get this frameProcessor running without `react-native-reanimated`. I used
> 
> ```
>     "react-native-vision-camera": "3.9.2",
>     "react-native-vision-camera-v3-text-recognition": "1.0.4",
>     "react-native-worklets-core": "0.4.0",
> ```
> 
> I tried with the following settings:
> 
> ```
> const device = useCameraDevice('back', { physicalDevices: ['ultra-wide-angle-camera', 'wide-angle-camera'] })
> <Camera
>     audio={false}
>     callback={(data: object) => onTextRecognized(data)}
>     device={device}
>     fps={30}
>     isActive={visible}
>     options={{
>       language: 'latin',
>     }}
>     pixelFormat='yuv'
>     resizeMode='cover'
>     style={{
>       height: 400,
>       alignItems: 'center',
>       width: '90%',
>     }}
> >
> ```
> 
> However, I just get random output:
> 
> ```
> size: 14
> blockFrameBottom: 1127
> blockFrameLeft: 964
> blockFrameRight: 971
> blockFrameTop: 1120
> blockText: V
> elementFrameBottom: 1127
> elementFrameLeft: 964
> elementFrameRight: 971
> elementFrameTop: 1120
> elementText: V
> lineFrameBottom: 1127
> lineFrameLeft: 964
> lineFrameRight: 971
> lineFrameTop: 1120
> lineText: V
> resultText: V
> size: 7
> blockFrameBottom: 1136
> blockFrameLeft: 1040
> blockFrameRight: 1052
> blockFrameTop: 1126
> blockText: A
> elementFrameBottom: 1136
> elementFrameLeft: 1040
> elementFrameRight: 1052
> elementFrameTop: 1126
> elementText: A
> lineFrameBottom: 1136
> lineFrameLeft: 1040
> lineFrameRight: 1052
> lineFrameTop: 1126
> lineText: A
> resultText: M
> ```
> 
> I tried with all orientations. Can you give some advice on how to configure camera (e.g. resolution, aspect ratio, fps, pixel format) to get the best results?

I see you are scanning a letter, not a text, so your result is the same. Have you tried scanning large text and the result is the same?

**Comment by gldkru** [comment]
@gev2002 I scan text and the result same

**Comment by pedrol2b** [comment]
Works fine for me 🤔

**Comment by pedrol2b** [comment]
Made a minimal reproduction repository, and seems to be working fine. Well at least works on my machine 🤓 
https://github.com/pedrol2b/example-v3-text-recognition

**Comment by gev2002** [comment]
Hello. I tested it on many devices, Android works everywhere, but in iOS sometimes normal result sometimes same. I’ll try to find a problem and fix it.

**Comment by thongquach** [comment]
Is there any ETA on this one, @gev2002 ? Thanks in advance.

**Comment by gev2002** [comment]
> Is there any ETA on this one, @gev2002 ? Thanks in advance.

Now I can’t say the exact time when I will do this, I’m very busy right now. I'll do it when I have free time.

**Comment by eobruno** [comment]
It worked great on Android, but I couldn't get it to work on IOS.
I'm looking forward to it being resolved soon. Thanks!

**Comment by rvera** [comment]
Same issue here, it builds and runs but generates random gibberish, mostly just "M", "W" and "*" characters
