### ISSUE TITLE
docs(Performance): update docs on performance tips and how to properly setup

### ISSUE THREAD

**Issue by pedrol2b** [gev2002/react-native-vision-camera-v3-text-recognition#10]
# Documentation Update Suggestion

## Summary
On Android devices, the plugin experiences poor performance in the frame processor, as reported in the [Discord logs](https://discord.com/channels/1147256486762913884/1147256775293272124/1234908214773026816). However, a few "tweaks" can be made to improve the frame processor performance.

## Proposed Update
Add tips to the [README](https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/blob/main/README.md) on properly setting up the frame processor plugin to enhance performance.

## Information
The performance issue with the frame processor plugin can be addressed in two ways.
https://github.com/ismaelsousa/vision-camera-ocr/issues/9#issuecomment-2086301428

### Solution 1
For now, in [react-native-vision-camera v4](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0), you can patch the `CameraSession.kt` file with:

```kt
val analyzer = ImageAnalysis.Builder().also { analysis ->

// Replace this       analysis.setBackpressureStrategy(ImageAnalysis.STRATEGY_BLOCK_PRODUCER)
// With this        analysis.setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
```
This change alone can significantly improve the performance of ImageAnalysis.

> You can read more about this solution here https://github.com/mrousavy/react-native-vision-camera/issues/2826

### Solution 2
For frame processor implementation, instead of solely using [`runAtTargetFps`](https://react-native-vision-camera.com/docs/api/#runattargetfps) for throttling the frame processing, you could use [`runAsync`](https://react-native-vision-camera.com/docs/api/#runasync) to significantly improve the frame processing performance while still being able to throttle the frames if needed.

Here's an example:
```tsx
  /** Process camera frames */
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
    runAtTargetFps(10, () => {
      runAsync(frame, () => {
        'worklet'
        const text: TextDataMap = scanText(frame, { language: 'latin' })
        console.log(text)
      })
    })
  }, [])
```

> [!IMPORTANT]  
> If you're using the Reanimated plugin in Babel, be sure to update the `babel.config` to include `processNestedWorklets` to avoid any [Regular JavaScript function cannot be shared..](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aissue+Frame+Processor+Error%3A+Regular+javascript+function+%27%27+cannot+be+shared.+Try+decorating+the+function+with+the+%27worklet%27+keyword+to+allow+the+javascript+function+to+be+used+as+a+worklet.%2C+js+engine%3A+VisionCamera) errors.

## Screenshots
![image](https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/assets/107975184/f94f322e-fe31-420d-bb80-c02a256719d9)
![image](https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/assets/107975184/bf4381bf-a30c-4320-944c-df2d414599b1)

## Related Issues/Pull Requests
https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/issues/9
https://github.com/mrousavy/react-native-vision-camera/issues/2826
https://github.com/ismaelsousa/vision-camera-ocr/issues/9#issuecomment-2086301428
https://react-native-vision-camera.com/docs/guides/performance

**Comment by gev2002** [comment]
Great Idea ! We can do it in Vision Camera V4.
