### ISSUE TITLE
[Bug] Missing line details and element details

### ISSUE THREAD

**Issue by tfcornerstone** [gev2002/react-native-vision-camera-v3-text-recognition#11]
Currently the line details and element details are of the last line and last element with in the block.

```TextData = {
  blockFrameBottom: number;
  blockFrameLeft: number;
  blockFrameRight: number;
  blockFrameTop: number;
  blockText: string;
  elementFrameBottom: number;
  elementFrameLeft: number;
  elementFrameRight: number;
  elementFrameTop: number;
  elementText: string;
  lineFrameBottom: number;
  lineFrameLeft: number;
  lineFrameRight: number;
  lineFrameTop: number;
  lineText: string;
  resultText: string;
  size: number;
};

// Should be:

TextData = {
  blockFrameBottom: number;
  blockFrameLeft: number;
  blockFrameRight: number;
  blockFrameTop: number;
  blockText: string;
  lines: array {
               lineFrameBottom: number;
               lineFrameLeft: number;
               lineFrameRight: number;
               lineFrameTop: number;
               lineText: string;
               elements: array {
                       elementFrameBottom: number;
                         elementFrameLeft: number;
                         elementFrameRight: number;
                         elementFrameTop: number;
                         elementText: string;
               }
   }
  resultText: string;
  size: number;
};```

**Comment by gev2002** [comment]
> Currently the line details and element details are of the last line and last element with in the block.
> 
> ```
>   blockFrameBottom: number;
>   blockFrameLeft: number;
>   blockFrameRight: number;
>   blockFrameTop: number;
>   blockText: string;
>   elementFrameBottom: number;
>   elementFrameLeft: number;
>   elementFrameRight: number;
>   elementFrameTop: number;
>   elementText: string;
>   lineFrameBottom: number;
>   lineFrameLeft: number;
>   lineFrameRight: number;
>   lineFrameTop: number;
>   lineText: string;
>   resultText: string;
>   size: number;
> };
> 
> // Should be:
> 
> TextData = {
>   blockFrameBottom: number;
>   blockFrameLeft: number;
>   blockFrameRight: number;
>   blockFrameTop: number;
>   blockText: string;
>   lines: array {
>                lineFrameBottom: number;
>                lineFrameLeft: number;
>                lineFrameRight: number;
>                lineFrameTop: number;
>                lineText: string;
>                elements: array {
>                        elementFrameBottom: number;
>                          elementFrameLeft: number;
>                          elementFrameRight: number;
>                          elementFrameTop: number;
>                          elementText: string;
>                }
>    }
>   resultText: string;
>   size: number;
> };```
> ```

It was a bug with types, I already fixed it.
