### ISSUE TITLE
Add CREDIT_CARD and DOCUMENT language options

### ISSUE THREAD

**Issue by daveyjones** [gev2002/react-native-vision-camera-v3-text-recognition#12]
It looks like `CREDIT_CARD` and `DOCUMENT` are both available as `LanguageOptions`.

https://developers.google.com/android/reference/com/google/mlkit/vision/text/TextRecognizerOptionsInterface

It would be great to expose those options in this library. I'm personally interested in the `CREDIT_CARD` option.

**Comment by gev2002** [comment]
> It looks like `CREDIT_CARD` and `DOCUMENT` are both available as `LanguageOptions`.
> 
> https://developers.google.com/android/reference/com/google/mlkit/vision/text/TextRecognizerOptionsInterface
> 
> It would be great to expose those options in this library. I'm personally interested in the `CREDIT_CARD` option.

Yes, It would be great to. I will do it soon, But For Vision Camera V4 version.
