### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by daveyjones** [gev2002/react-native-vision-camera-v3-text-recognition#13]
On iOS, I'm getting output like this:

```
2024-05-01 01:57:54.577400-0700 PayTrace[11145:588658] [javascript] [], 666
2024-05-01 01:57:54.577777-0700 PayTrace[11145:588658] [javascript] []
2024-05-01 01:57:54.752143-0700 PayTrace[11145:588658] [javascript] [], 666
2024-05-01 01:57:54.752527-0700 PayTrace[11145:588658] [javascript] []
2024-05-01 01:57:54.986440-0700 PayTrace[11145:588658] [javascript] [ { blockFrameBottom: 848,
    blockFrameLeft: 624,
    blockFrameRight: 689,
    blockFrameTop: 831,
    blockText: 'sssFEE',
    elementFrameBottom: 848,
    elementFrameLeft: 624,
    elementFrameRight: 689,
    elementFrameTop: 831,
    elementText: 'sssFEE',
    lineFrameBottom: 848,
    lineFrameLeft: 624,
    lineFrameRight: 689,
    lineFrameTop: 831,
    lineText: 'sssFEE',
    resultText: 'sssFEE',
    size: 17 } ], 666
2024-05-01 01:57:54.988704-0700 PayTrace[11145:588658] [javascript] [ { blockFrameBottom: 848,
    blockFrameLeft: 624,
    blockFrameRight: 689,
    blockFrameTop: 831,
    blockText: 'sssFEE',
    elementFrameBottom: 848,
    elementFrameLeft: 624,
    elementFrameRight: 689,
    elementFrameTop: 831,
    elementText: 'sssFEE',
    lineFrameBottom: 848,
    lineFrameLeft: 624,
    lineFrameRight: 689,
    lineFrameTop: 831,
    lineText: 'sssFEE',
    resultText: 'sssFEE',
    size: 17 } ]
2024-05-01 01:57:55.196959-0700 PayTrace[11145:588658] [javascript] [], 666
2024-05-01 01:57:55.197466-0700 PayTrace[11145:588658] [javascript] []
2024-05-01 01:57:55.398833-0700 PayTrace[11145:588658] [javascript] [], 666
2024-05-01 01:57:55.399397-0700 PayTrace[11145:588658] [javascript] []
```

I'll try to create an isolated repo to reproduce, but just wanted to post this here to see if anyone else is seeing something similar.

**Comment by gev2002** [comment]
> On iOS, I'm getting output like this:
> 
> ```
> 2024-05-01 01:57:54.577400-0700 PayTrace[11145:588658] [javascript] [], 666
> 2024-05-01 01:57:54.577777-0700 PayTrace[11145:588658] [javascript] []
> 2024-05-01 01:57:54.752143-0700 PayTrace[11145:588658] [javascript] [], 666
> 2024-05-01 01:57:54.752527-0700 PayTrace[11145:588658] [javascript] []
> 2024-05-01 01:57:54.986440-0700 PayTrace[11145:588658] [javascript] [ { blockFrameBottom: 848,
>     blockFrameLeft: 624,
>     blockFrameRight: 689,
>     blockFrameTop: 831,
>     blockText: 'sssFEE',
>     elementFrameBottom: 848,
>     elementFrameLeft: 624,
>     elementFrameRight: 689,
>     elementFrameTop: 831,
>     elementText: 'sssFEE',
>     lineFrameBottom: 848,
>     lineFrameLeft: 624,
>     lineFrameRight: 689,
>     lineFrameTop: 831,
>     lineText: 'sssFEE',
>     resultText: 'sssFEE',
>     size: 17 } ], 666
> 2024-05-01 01:57:54.988704-0700 PayTrace[11145:588658] [javascript] [ { blockFrameBottom: 848,
>     blockFrameLeft: 624,
>     blockFrameRight: 689,
>     blockFrameTop: 831,
>     blockText: 'sssFEE',
>     elementFrameBottom: 848,
>     elementFrameLeft: 624,
>     elementFrameRight: 689,
>     elementFrameTop: 831,
>     elementText: 'sssFEE',
>     lineFrameBottom: 848,
>     lineFrameLeft: 624,
>     lineFrameRight: 689,
>     lineFrameTop: 831,
>     lineText: 'sssFEE',
>     resultText: 'sssFEE',
>     size: 17 } ]
> 2024-05-01 01:57:55.196959-0700 PayTrace[11145:588658] [javascript] [], 666
> 2024-05-01 01:57:55.197466-0700 PayTrace[11145:588658] [javascript] []
> 2024-05-01 01:57:55.398833-0700 PayTrace[11145:588658] [javascript] [], 666
> 2024-05-01 01:57:55.399397-0700 PayTrace[11145:588658] [javascript] []
> ```
> 
> I'll try to create an isolated repo to reproduce, but just wanted to post this here to see if anyone else is seeing something similar.

Hello,  I am update plugin, can you try now for me,everything is OK :)
