### ISSUE TITLE
Vision Camera V4 & new architecture (react-native 0.74+) support  

### ISSUE THREAD

**Issue by 404-html** [gev2002/react-native-vision-camera-v3-text-recognition#14]
There's a plan to [migrate](https://github.com/mrousavy/react-native-vision-camera/issues/2614) Vision Camera (V4 only) to the new architecture, so it runs on react-native 0.74+.

It would be nice to follow up with these updates and make plugin working on this setup too.

**Comment by gev2002** [comment]
> There's a plan to [migrate](https://github.com/mrousavy/react-native-vision-camera/issues/2614) Vision Camera (V4 only) to the new architecture, so it runs on react-native 0.74+.
> 
> It would be nice to follow up with these updates and make plugin working on this setup too.

This plugin is for vision camera v3 but I will create new plugin for v4.I have already create 2 new plugins for v4
https://github.com/gev2002/react-native-vision-camera-barcodes-scanner, https://github.com/gev2002/react-native-vision-camera-image-labeler

**Comment by coder-xiaomo** [comment]
Thanks for the author's open source project, which has helped me a lot. I would like to know, is it a big workload to migrate v4 to new architecture, and does it take a lot of time and energy?

I am preparing to migrate to react native 0.74.1, but this project does not support the new architecture at present, I would like to know how long will it be appropriate to migrate, such as weeks, months, or even longer?

Thanks again for the author's open source project, which has helped me a lot!

**Comment by beatlecz** [comment]
Text recognition would be great!!! Any idea when you will do text recognition for V4? I would be very grateful for that

**Comment by gev2002** [comment]
> Text recognition would be great!!! Any idea when you will do text recognition for V4? I would be very grateful for that

I can't say specific time now. I'm very busy right now, when I have free time I'll do it.

**Comment by Anj-interactivated** [comment]
@gev2002 that would be great

**Comment by 404-html** [comment]
I managed to port Android, working on iOS now: https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/pull/17
