### ISSUE TITLE
VisionCameraProxy.h has to be compiled with C++!

### ISSUE THREAD

**Issue by cameronbrown23** [gev2002/react-native-vision-camera-v3-text-recognition#15]
<img width="256" alt="Screenshot 2024-05-06 at 18 01 20" src="https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/assets/90785106/ad28ea9b-c91e-41d0-8132-1dc3a34545c0">

I am trying to get this plugin working with my React Native project but I am getting the errors shown above during the Xcode build.. 
I have the following package versions installed:

"react-native": "^0.74.1",
"react-native-vision-camera": "^4.0.2",
"react-native-vision-camera-v3-text-recognition": "^1.1.1",
"react-native-worklets-core": "^1.3.0",

I am **not** using react-native-reanimate.

Any pointers on what could be causing these errors? Seems like a package incompatibility issue. I tried installing with:
"react-native-worklets-core": "^0.5.0" but I get the same errors.

**Comment by gev2002** [comment]
You are trying to use this module with React Native 0.74.1 and Vision Camera v4. This plugin is for Vision Camera V3 and react native below 0.74.0.

**Comment by cameronbrown23** [comment]
@gev2002 Thank you for the update. I'm now running it on 0.73.7. Unfortunately I'm unable to get it to work on iOS (iPhone 15). I get outputs that look like the following:

 LOG  {"0": {"blockFrameBottom": 193, "blockFrameLeft": 756, "blockFrameRight": 764, "blockFrameTop": 158, "blockText": "M", "elementFrameBottom": 193, "elementFrameLeft": 756, "elementFrameRight": 764, "elementFrameTop": 158, "elementText": "M", "lineFrameBottom": 193, "lineFrameLeft": 756, "lineFrameRight": 764, "lineFrameTop": 158, "lineText": "M", "resultText": "M", "size": 35}} data

It will output random letters that are not in the frame of reference. I've been reading through the issue requests and other people seem to be having similar issues on iOS. Is this something you're looking to fix and if so are you able to provide rough timescales?

FYI - I am trying to use your plugin for number plate scanning.
