### ISSUE TITLE
React Native BUILD FAILED on run-ios

### ISSUE THREAD

**Issue by HieeusNguyen** [gev2002/react-native-vision-camera-v3-text-recognition#16]
I followed the steps in the documentation but ended up receiving this error. This error only appeared when I tried to restart it with npx react-native run-ios

** BUILD FAILED **

The following build commands failed:
        CompileC /Users/hieu/Library/Developer/Xcode/DerivedData/VMG4-gvwtohzfzveebgepkorvlhstazyf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/VisionCamera.build/Objects-normal/arm64/JSINSObjectConversion.o /Users/hieu/WorkPlace/ReactNative/VMG4/node_modules/react-native-vision-camera/ios/Frame\ Processor/JSINSObjectConversion.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'VisionCamera' from project 'Pods')
(1 failure)

React-native: 0.74.1
Xcode: 15.3
iOS: 17.4
react-native-vision-camera: 3.9.2 (The version has been updated to be compatible with react-native-vision-camera-v3-text-recognition), 
react-native-worklets-core: 0.5.0 (The version has been updated to be compatible with react-native-vision-camera-v3-text-recognition),
react-native-vision-camera-v3-text-recognition: 1.1.1,

This is my first time writing this, so if there are any issues, I hope everyone can understand and support me so that I can fix this error. Thank you very much

**Comment by pedrol2b** [comment]
Hey 👋🏻, so as far as i'm concerned until today

[react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera) does not yet fully support react-native: 0.74.1
so my guess is that the error that you're seeing is on their side;

![image](https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/assets/107975184/368606d4-6a6a-437e-8456-0e74bd5664da)

https://github.com/mrousavy/react-native-vision-camera/issues/2614

**Comment by HieeusNguyen** [comment]
So, at the present time, how can this issue be resolved? And can the function scanText() accept an argument that is the path of the image?

**Comment by gev2002** [comment]
Why, are you need to path of image?

**Comment by HieeusNguyen** [comment]
I want to add the functionality to recognize text from images in the gallery. It would be great if this feature could be added. Thank you very much.

**Comment by pedrol2b** [comment]
> I want to add the functionality to recognize text from images in the gallery. It would be great if this feature could be added. Thank you very much.

Even tho is technically possible to implement this feature as you could create an `InputImage` from a file

[using-a-file-uri](https://developers.google.com/ml-kit/vision/barcode-scanning/android#using-a-file-uri)
```kt
val image: InputImage
try {
    image = InputImage.fromFilePath(context, uri)
} catch (e: IOException) {
    e.printStackTrace()
}
```

i think that kinda miss the porpouse of this package and the integration with react-native-vision-camera;

maybe take a look at
https://github.com/a7medev/react-native-ml-kit

**Comment by HieeusNguyen** [comment]
Great! So how do I use the vision-camera-v3-text-recognition library at the moment? I have used react-native version 0.73.6, vision-camera 3.9.2 and worklets-core 0.5.0 but still encounter the error above. Thank you for your enthusiastic support.

**Comment by gev2002** [comment]
You can now use the plugin for version 4. The V4 plugin is out now! 🥳 https://github.com/gev2002/react-native-vision-camera-text-recognition
