### ISSUE TITLE
Give a full example code

### ISSUE THREAD

**Issue by PeaGo** [gev2002/react-native-vision-camera-v3-text-recognition#7]
I'm using your library, but it doesn't seem to be working. Could you provide an example of how to use your library? Thanks in advance.

**Comment by gev2002** [comment]
> I'm using your library, but it doesn't seem to be working. Could you provide an example of how to use your library? Thanks in advance.

// This is example usage full code

import React, { useState } from 'react';
import { StyleSheet } from 'react-native';
import { useCameraDevice } from 'react-native-vision-camera';
import { Camera } from 'react-native-vision-camera-v3-text-recognition';

const CameraExample = () => {
  const device = useCameraDevice('back');
  const [data, setData] = useState(null);

  console.log(data , 'data');
  return (
    <>
      {!!device && (
        <Camera
          callback={(d) => setData(d)}
          style={StyleSheet.absoluteFill}
          options={{
            language: 'latin',
          }}
          device={device}
          isActive
        />
      )}
    </>
  );
}

export default CameraExample;
