### ISSUE TITLE
Camera lags during OCR operating even at 1 FPS

### ISSUE THREAD

**Issue by kevinranks** [gev2002/react-native-vision-camera-v3-text-recognition#9]
Hello and thank you for this library. 

I've been trying to implement text ocr and have noticed that every time the ocr/scanText operation runs the camera lags. I've tested this in my own app as well as the react-native-vision-camera example app.

At full fps it's extremely laggy but even at 1 fps it lags during the operation. I've gone as far as commenting out all of the native Android code except for the `recognizer.process(image)` and still experience the lag. I've also tested alternate ocr libraries with vision-camera v4 and have experienced the lag as well. On old versions of vision-camera I did not experience this issue.

Tested on Android emulator,  S21 Ultra, and S24 Ultra both built to device & release builds.

```
"react-native-vision-camera-v3-text-recognition": "^1.1.0",
"react-native-vision-camera": "^4.0.1",
"react-native-worklets-core": "^1.2.0",
```

Code Sample:

```js
import React from 'react'
import { StyleSheet } from 'react-native'
import { Camera, runAtTargetFps, useCameraDevice, useFrameProcessor } from 'react-native-vision-camera'
import { useTextRecognition } from 'react-native-vision-camera-v3-text-recognition'

export function App() {
  const device = useCameraDevice('back')
  const options = { language: 'latin' }
  const { scanText } = useTextRecognition(options)
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
    runAtTargetFps(1, () => {
      'worklet'
      const data = scanText(frame)
      console.log(data, 'data')
    })
  }, [])
  return <>{!!device && <Camera style={StyleSheet.absoluteFill} device={device} isActive frameProcessor={frameProcessor} />}</>
}
```

The attached video shows how the fps is good while my hand is in front of the camera but when it encounters text it lags. 

https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/assets/6843831/7ad8aaaf-0e5a-4cea-bb4c-79093364ee87

Does anyone have a working demo showing that it can perform ocr without camera lag?

**Comment by DanInDev** [comment]
Currently the scanText worklet is running on the same thread as the frameProcessor and Camera, which blocks the display for new frames until the scan has been completed.
 
Since, depending on the amount of text, it takes longer you should run it async like this:
 
```javaScript
 const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
  runAsync(frame, () => {
      'worklet'
      const data = scanText(frame)
      console.log(data, 'data')
    })
  }, [])
```

**Comment by gev2002** [comment]
This Package is not working now on Vision Camera V4. I change logic and I Will create new package for all plugins and do it for Vision Camera V4.Thanks !
